modLoader = "javafml"
loaderVersion = "[2,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
displayTest = "IGNORE_SERVER_VERSION"
description = '''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "neoforgeskyboxes.mixins.json"

[[mixins]]
config = "neoforgeskyboxes_interop.mixins.json"
