org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
loom.platform=neoforge

mod_id=neoforgeskyboxes
mod_name=NeoforgeSkyboxes
mod_version=0.1.1
mod_group_id=dev.hoshno
mod_authors=HoshnoHikari
mod_license=MIT
mod_description=Unofficial NeoForge custom skybox support compatible with FabricSkyBoxes/Nuit resource pack formats.

minecraft_version=1.21.1
neoforge_version=21.1.15
